### ISSUE TITLE
Is an Apache 2.0 License a possibility?

### ISSUE THREAD

**Issue by jaxonshi** [coltekin/TRmorph#14]
Since [foma](https://code.google.com/p/foma/) was recently re-released under the more commercially friendly Apache 2.0 license, I was wondering if there's any chance you might consider a release of TRmorph under the same.

**Comment by thorn0** [comment]
What's commercially unfriendly about LGPL?

**Comment by coltekin** [comment]
I also think that LGPL should be fine for most commercial usage. However, since it has been a rather frequent question lately, I have just switched to the MIT license. As I understand, this should be compatible with almost all commercial or open-source usage.

My main reason for initial (L)GPL was the hope that the improvements outside here may find their way back. Other than that, I do not have much of a "preference" among many open-source licenses out there. So, although the license does not dictate it now, if you improve it in some way, please consider sending a patch.
