### ISSUE TITLE
Compiling TRMorph on Mac OSX gives error

### ISSUE THREAD

**Issue by eakarsu** [coltekin/TRmorph#9]
I compiled foma successfully and having issues with TRMorph on Mac.

I try to compile TRMorh on Mac OSX but getting problem. Can you help me?

orph.lexc:892:22: error: invalid preprocessing directive
                    #;
                     ^
morph.lexc:947:22: error: invalid preprocessing directive
                    #;
                     ^
morph.lexc:982:18: error: invalid preprocessing directive
                #;
                 ^
morph.lexc:995:18: error: invalid preprocessing directive

**Comment by evanmiltenburg** [comment]
I also had issues on my mac, but I just compiled the fst file on a Linux computer and I can just use the fst file with foma on my mac. Maybe it's possible to have an "official" compiled fst file in this repository?

**Comment by keryil** [comment]
I am writing this for future reference for everybody in case Cagri doesn't have time to fix this one, as the workaround is quite simple, and only depends on Homebrew. People often use Homebrew to install foma on OS/X anyway. 

The way I work around this issue is:

1. Install GCC (through Homebrew). 
2. Discover the GCC binary. It is not `/usr/bin/gcc`, which is an alias for `clang` compiler on OS/X. It is often something along the lines of `gcc-4.9` (depending on the version, of course). Confirm you got the right one by issuing the command   `gcc-4.9 -v`. The output should tell you the details of the compiler. Look for words `clang` and `homebrew` to distinguish between the two, and makre sure you get the one that contains `homebrew`. 
3. Modify the Makefile of the project (i.e. the file called Makefile in the TRmorph root). Find the lines that start with `CPP=gcc...` and `MAKEDEP=gcc...`, and replace `gcc` with the GCC binary you located in the previous step e.g. `gcc-4.9`.
4. Make. 

Hope this helps.

**Comment by snomos** [comment]
Installing & using GCC is not an option for me. Could a solution be to replace all #'s with a reference to a new lexicon ENDLEX, and then define that lexicon as follows?

```
LEXICON ENDLEX # ;
```

That should hopefully resolve the issue, by "protecting" the hash mark using the preceding text.

**Comment by snomos** [comment]
That pull request only solves the issue with #. Now I have a number of the following errors:

```
In file included from analyzer.lexc:43:
./lexicon/punctuation:8:17: error: invalid preprocessing directive
%:              Punc;
                ^
In file included from analyzer.lexc:51:
./lexicon/emoticon:37:4: error: invalid preprocessing directive
 %:-)           Interjection;
   ^
...
```

The problem seems to be the sequence `%:`. And in this case it is not easy to see how to change the code to make it pass the macOS C++ preprocessor, not without seriously garbling the lexc code. Suggestions welcome :-)
